name: Generate iCalendar File

on:
  push:
    branches:
      - main
    paths:
      - 'events.json'
      - 'scripts/generate_ics.py'
  workflow_dispatch: # Allows manual triggering

jobs:
  generate_calendar_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Or a newer stable version like 3.11

      - name: Install Python dependencies
        run: pip install ics

      - name: Run script to generate events.ics
        run: python scripts/generate_ics.py

      - name: Commit and push if events.ics changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          # Check if there are changes in the working directory for assets/events.ics
          if ! git diff --quiet assets/events.ics; then
            echo "Changes detected in assets/events.ics."
            git add assets/events.ics
            git commit -m "Update events.ics from workflow"
            git push
          else
            echo "No changes to assets/events.ics. Nothing to commit."
          fi
```
